// <auto-generated />
using System;
using MAVN.Service.SmartVouchers.MsSqlRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MAVN.Service.SmartVouchers.MsSqlRepositories.Migrations
{
    [DbContext(typeof(SmartVouchersContext))]
    partial class SmartVouchersContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("smart_vouchers")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MAVN.Service.SmartVouchers.MsSqlRepositories.Entities.PaymentRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<string>("VoucherShortCode")
                        .IsRequired()
                        .HasColumnName("short_code")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("VoucherShortCode");

                    b.ToTable("payment_request");
                });

            modelBuilder.Entity("MAVN.Service.SmartVouchers.MsSqlRepositories.Entities.VoucherCampaignContentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnName("campaign_id")
                        .HasColumnType("uuid");

                    b.Property<int>("ContentType")
                        .HasColumnName("content_type")
                        .HasColumnType("integer");

                    b.Property<int>("Language")
                        .HasColumnName("language")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnName("value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("campaign_content");
                });

            modelBuilder.Entity("MAVN.Service.SmartVouchers.MsSqlRepositories.Entities.VoucherCampaignEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("uuid");

                    b.Property<int>("BoughtVouchersCount")
                        .HasColumnName("bought_vouchers_count")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnName("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnName("creation_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnName("currency")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnName("description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnName("expiration_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FromDate")
                        .HasColumnName("from_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("text");

                    b.Property<Guid>("PartnerId")
                        .HasColumnName("partner_id")
                        .HasColumnType("uuid");

                    b.Property<short>("State")
                        .HasColumnName("state")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("ToDate")
                        .HasColumnName("to_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("VoucherPrice")
                        .HasColumnName("voucher_price")
                        .HasColumnType("numeric");

                    b.Property<int>("VouchersTotalCount")
                        .HasColumnName("vouchers_total_count")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("campaign");
                });

            modelBuilder.Entity("MAVN.Service.SmartVouchers.MsSqlRepositories.Entities.VoucherEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<Guid>("CampaignId")
                        .HasColumnName("campaign_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnName("owner_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnName("purchase_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnName("redemption_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("SellerId")
                        .HasColumnName("seller_id")
                        .HasColumnType("uuid");

                    b.Property<string>("ShortCode")
                        .HasColumnName("short_code")
                        .HasColumnType("text");

                    b.Property<short>("Status")
                        .HasColumnName("status")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("voucher");
                });

            modelBuilder.Entity("MAVN.Service.SmartVouchers.MsSqlRepositories.Entities.VoucherValidationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ValidationCode")
                        .IsRequired()
                        .HasColumnName("validation_code")
                        .HasColumnType("text");

                    b.Property<long>("VoucherId")
                        .HasColumnName("voucher_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("VoucherId")
                        .IsUnique();

                    b.ToTable("voucher_validation");
                });

            modelBuilder.Entity("MAVN.Service.SmartVouchers.MsSqlRepositories.Entities.VoucherCampaignContentEntity", b =>
                {
                    b.HasOne("MAVN.Service.SmartVouchers.MsSqlRepositories.Entities.VoucherCampaignEntity", null)
                        .WithMany("LocalizedContents")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MAVN.Service.SmartVouchers.MsSqlRepositories.Entities.VoucherValidationEntity", b =>
                {
                    b.HasOne("MAVN.Service.SmartVouchers.MsSqlRepositories.Entities.VoucherEntity", null)
                        .WithOne("Validation")
                        .HasForeignKey("MAVN.Service.SmartVouchers.MsSqlRepositories.Entities.VoucherValidationEntity", "VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
